In [3]:
import numpy as np

1. Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [10]:
arr = np.random.randint(0,20,20)
print(arr)
cond = (arr > 3) & (arr < 8)
arr[cond] *= -1
print(arr)

[ 1  6 12  6  5  4 15  7 18  5 11  8  3  6  6 17  3 14  4 16]
[ 1 -6 12 -6 -5 -4 15 -7 18 -5 11  8  3 -6 -6 17  3 14 -4 16]


2. Заменить максимальный элемент случайного массива на 0

In [16]:
arr = np.random.randint(0,20,10)
print(arr)
max_index = np.argmax(arr)
arr[max_index] = 0
print(arr)

[17 10 18 15  5 18 14 10  4 15]
[17 10  0 15  5 18 14 10  4 15]


3. Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [19]:
from itertools import product

data_2d = np.array([
    ['A', 'B'], 
    [1, 2]    
])

row1 = data_2d[0,:]
row2 = data_2d[1,:]
# print(row1)
# print(row2)

comb = product(row1, row2)
res = np.array(list(comb))
print(res)

[['A' '1']
 ['A' '2']
 ['B' '1']
 ['B' '2']]


4. Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B <br>
Уточнение: строка в A должна состоять из элементов в B, но это не значит что она должна содержать все эл-ты из B

In [20]:
A = np.array([
    [1, 2, 3],
    [1, 9, 4],
    [2, 3, 4],
    [3, 4, 5],
    [1, 2, 3],
    [1, 2, 4],
    [6, 3, 4],
    [3, 4, 5]
])

B = np.array([
    [1, 2],
    [3, 4]
])

el = np.unique(B)
mask = np.isin(A, el)

rows_ok = np.all(mask, axis=1)
res = A[rows_ok]
print(res)

[[1 2 3]
 [2 3 4]
 [1 2 3]
 [1 2 4]]


5. Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)<br>
ключевая идея: удаляем строку , если min == max

In [21]:
A = np.array([
    [1, 1, 1],
    [2, 2, 3],
    [4, 4, 4],
    [5, 6, 5],
    [7, 7, 8],
    [9, 9, 9],
    [1, 2, 3],
    [3, 3, 3],
    [4, 5, 4],
    [6, 6, 6]
])

row_min = A.min(axis=1)
row_max = A.max(axis=1)
mask = row_min != row_max
print(A[mask])

[[2 2 3]
 [5 6 5]
 [7 7 8]
 [1 2 3]
 [4 5 4]]


6.Дан двумерный массив. Удалить те строки, которые повторяются

In [23]:
A = np.array([
    [1, 1, 1],
    [2, 2, 3],
    [4, 4, 4],
    [5, 6, 5],
    [7, 7, 8],
    [60, 60, 60],
    [1, 2, 3],
    [3, 3, 3],
    [4, 5, 4],
    [60, 60, 60]
])

unique_rows = np.unique(A, axis=0)
print(unique_rows)

[[ 1  1  1]
 [ 1  2  3]
 [ 2  2  3]
 [ 3  3  3]
 [ 4  4  4]
 [ 4  5  4]
 [ 5  6  5]
 [ 7  7  8]
 [60 60 60]]


Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).

Задача 1: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.
Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [39]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
diag = np.diagonal(X)
non_zero = diag[diag != 0]
res = np.prod(non_zero)
print(res)

X_list = X.tolist()
res_list = 1
for i in range(min(len(X_list),len(X_list[0]))):
    if X_list[i][i] != 0:
        res_list *= X_list[i][i] 

print(res_list)


3
3


Задача 2: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.
Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [43]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

res = np.array_equal(np.sort(x), np.sort(y))
print(res)

x_list = x.tolist()
y_list = y.tolist()

res_list = sorted(x_list) == sorted(y_list)
print(res_list)

True
True


Задача 3: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [ ]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
x_list = x.tolist()
inter_res_list = []
for i in range(1,len(x_list)):
    if x_list[i-1] == 0:
        inter_res_list.append(x_list[i])
print(max(inter_res_list))


mask = x[:-1] == 0 # все, кроме последнего
candidates = x[1:][mask] #беру эл-ты со второго и до конца
print(candidates.max())

5
5


Задача 4: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.
Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [54]:
x = np.array([2, 2, 2, 3, 3, 3, 5])
print(np.unique(x,return_counts=True))

x_list = x.tolist()
count_dict = {}

for el in x_list:
    if el in count_dict.keys():
        count_dict[el] += 1
    else:
        count_dict[el] = 1

print(count_dict.keys(), count_dict.values())

(array([2, 3, 5]), array([3, 3, 1]))
dict_keys([2, 3, 5]) dict_values([3, 3, 1])


Задача 5: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [59]:
import time
from scipy.spatial.distance import cdist
import math 

def euclidean_distances_numpy(X, Y):
    diff = X[:, np.newaxis, :] - Y[np.newaxis, :, :]
    return np.sqrt(np.sum(diff**2, axis=2))


X = np.random.rand(1000, 50)
Y = np.random.rand(1000, 50)


start = time.time()
D1 = euclidean_distances_numpy(X, Y)
t_numpy = time.time() - start


start = time.time()
D2 = cdist(X, Y)
t_scipy = time.time() - start

print("NumPy:", t_numpy)
print("SciPy:", t_scipy)


def euclidean_distances(X, Y):
    D = [] 
    for x in X: 
        row = []  
        for y in Y:  
            dist = math.sqrt(sum((xi - yi)**2 for xi, yi in zip(x, y)))
            row.append(dist)
        D.append(row)
    return D


X_list = [[1, 2], [3, 4]]
Y_list = [[5, 6], [7, 8], [9, 10]]

X_numpy = np.array(X_list)
Y_numpy = np.array(Y_list)

D = euclidean_distances(X_list, Y_list)
for row in D:
    print(row)

print(euclidean_distances_numpy(X_numpy, Y_numpy))

NumPy: 0.42110443115234375
SciPy: 0.026686906814575195
[5.656854249492381, 8.48528137423857, 11.313708498984761]
[2.8284271247461903, 5.656854249492381, 8.48528137423857]
[[ 5.65685425  8.48528137 11.3137085 ]
 [ 2.82842712  5.65685425  8.48528137]]
